In [1]:
import pandas as pd
import numpy as np
import hashlib as hb

In [2]:
sill_a = pd.read_csv('./data/問卷A班/程式語言學習策略量表A班.csv')
sill_b = pd.read_csv('./data/問卷B班/程式語言學習策略量表B班.csv')

In [3]:
sill_a.rename(columns={'學號 (Student ID)': 'username'}, inplace=True)
sill_b.rename(columns={'學號 (Student ID)': 'username'}, inplace=True)

In [4]:
sill_a['username'] = sill_a['username'].astype(str)
sill_b['username'] = sill_b['username'].astype(str)

In [5]:
### MD5
def md5(i):
    hl = hb.md5()
    
    hl.update(str(i).encode(encoding='utf-8'))

    #print('加密前為 ：' + str(i))
    #print('加密後為 ：' + hl.hexdigest())
    
    return hl.hexdigest()

In [6]:
sill_a['username'] = sill_a['username'].apply(md5)
sill_b['username'] = sill_b['username'].apply(md5)

In [7]:
sill_df = pd.merge(sill_a, sill_b, how = 'outer')

In [8]:
sill_df = sill_df.drop(columns=['時間戳記', '學校 (School)', '姓名(Name)'])

In [9]:
sill_df = sill_df.fillna(0)

In [10]:
def col(x):
    
    if x != 'username':
        x = x.split('.')[0]
        x = '#'+x

    return x

In [11]:
# list(sill_df)[1].split('.')[0]

sill_df.rename(columns= lambda x: col(x),inplace = True)

In [12]:


sill_df

,username,#1,#2,#3,#4,#5,#6,#7,#8,#9,...,#39,#40,#41,#42,#43,#44,#45,#46,#47,#48
0,b1dfc5c6ec04d46d1823c5fa972ad320,5,5,5,5,1,1,5,1,5,...,5,1,1,5,5,5,1,1,1,5
1,4e3519d7eafbfccdae231756fcf2ce9c,3,3,3,3,3,3,3,3,3,...,4,4,3,4,4,4,3,3,4,3
2,0cebfa477ed3e2e0c5a3f9aa96c23698,5,5,5,4,5,5,5,5,5,...,5,5,4,5,5,4,3,5,5,4
3,379bbc4c2c728db0a249e8c4e6b621af,3,3,3,3,3,3,5,3,5,...,5,1,4,5,5,5,5,5,5,5
4,a92f1708363527a34d93b0bc7840262c,3,4,3,3,2,2,4,4,3,...,4,3,3,3,4,3,2,3,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,b3544e076d49acb0dd2af969419895f0,4,5,2,2,4,2,3,3,4,...,3,3,1,1,4,2,1,1,1,1
100,c2e15430ed832457c780c948b21c37ec,4,2,2,3,3,1,2,4,2,...,4,4,1,4,5,4,3,4,1,2
101,8e72970e2fdad1fa564d800ba15d72c4,4,4,2,2,2,2,3,2,4,...,4,4,1,4,5,3,1,1,1,1
102,65e452ca8afdf0ba6a8cbc4af63da728,3,4,1,1,3,2,2,2,2,...,5,1,1,4,5,5,1,1,1,5
103,64d3bd3b339f63a66b8c878b561551d8,2,3,1,1,4,2,3,2,3,...,2,5,1,4,4,4,1,5,5,1

In [13]:
sill_df.to_csv('./output/sill.csv',encoding='utf8', index=False)

In [27]:
sill_df.shape

(104, 49)

In [14]:
# sill_be_a = pd.read_csv('./data/問卷A班/1092專注度&參與度問卷_A班.csv')
# sill_be_b = pd.read_csv('./data/問卷B班/1092專注度&參與度問卷_B班.csv')
# sill_af_a = pd.read_csv('./data/問卷A班/1092參與度問卷後測_A班.csv')
# sill_af_b = pd.read_csv('./data/問卷B班/1092參與度問卷後測_B班.csv')

In [15]:
# sill_be_a = sill_be_a.iloc[:,4:]
# sill_be_b = sill_be_b.iloc[:,4:]

# sill_af_a = sill_af_a.iloc[:,3:]
# sill_af_b = sill_af_b.iloc[:,3:]

In [16]:
# sill_be_a.rename(columns={'學號': 'username'},inplace=True)
# sill_be_b.rename(columns={'學號': 'username'},inplace=True)

# sill_af_a.rename(columns={'學號': 'username'},inplace=True)
# sill_af_b.rename(columns={'學號': 'username'},inplace=True)

In [17]:
# sill_be_a['id'] = sill_be_a['id'].astype(str)
# sill_be_b['id'] = sill_be_b['id'].astype(str)

# sill_af_a['id'] = sill_af_a['id'].astype(str)
# sill_af_b['id'] = sill_af_b['id'].astype(str)

In [18]:
# sill_be_a = sill_be_a[sill_be_a['id'].str.isdigit() == True]
# sill_be_b = sill_be_b[sill_be_b['id'].str.isdigit() == True]

# sill_af_a = sill_af_a[sill_af_a['id'].str.isdigit() == True]
# sill_af_b = sill_af_b[sill_af_b['id'].str.isdigit() == True]

In [19]:
# sill_af_b.iloc[0,32] = 0

In [20]:
# sill_be_df = pd.merge(sill_be_a,sill_be_b,how = 'outer')
# sill_af_df = pd.merge(sill_af_a,sill_af_b,how = 'outer')

In [21]:
# sill_be_df = sill_be_df[sill_be_df['id'].apply(lambda x: len(str(x))>=9)]
# sill_af_df = sill_af_df[sill_af_df['id'].apply(lambda x: len(str(x))>=9)]

In [22]:
# ### MD5
# def md5(i):
#     hl = hb.md5()
    
#     hl.update(str(i).encode(encoding='utf-8'))

#     #print('加密前為 ：' + str(i))
#     #print('加密後為 ：' + hl.hexdigest())
    
#     return hl.hexdigest()

# sill_be_df['id'] = sill_be_df['id'].apply(md5)
# sill_af_df['id'] = sill_af_df['id'].apply(md5)

In [23]:
# def col(x):
#     if x == '在上這門課之前，您是否學習過任何程式語言? 沒有請答無，有的話請填寫您學過哪些程式語言。':
#         return 'Before taking this course, have you learned any programming languages? No, please answer no. If yes, please fill in which programming languages you have learned.'
#     if x == '1. 在課前都會概覽(Survey)課程內容。':
#         return 'Before class overview (Survey) course content'
#     if x == '2. 我在課前都會針對課程內容進行自我提問(Question)。':
#         return 'I will ask myself questions about the content of the course before class(Question)'
#     if x == '3. 我在課前都有透過詳讀(Read)來預習課程內容。':
#         return 'I have prepared the content of the course through detailed reading before class'
#     if x == '4. 我在課堂的總結(Summary)活動，或是課後都會透過回想(Recall)來複習課程內容。':
#         return 'I will review the content of the course in the summary activity in the class or through the recall after the class.'
#     if x == '5. 我在課後，都會針對課程內容進行複習(Review)。':
#         return 'I will review the content of the course after class'
#     if x == '6. 我覺得SQ3R閱讀策略對我的學習是有幫助的。':
#         return 'I think SQ3R reading strategy is helpful to my study'
#     if x == '6. 我覺得填寫課程問卷對我的學習是有幫助的。':
#         return 'I think filling in the course questionnaire is helpful to my study'
#     if x == '針對問卷內容(參與度、SQ3R)，有甚麼想跟老師說的話':
#         return 'Regarding the questionnaire content (participation, SQ3R), what do you want to say to the teacher'
#     else:
#         return x

In [24]:
# ###translation
# sill_be_df.rename(columns={x: x.split('(')[0] for x in sill_be_df.columns[:11]},inplace=True)

# sill_be_df.rename(columns={x: x.split('.')[0]+'. '+x.split('(')[1].split(')')[0] for x in sill_be_df.columns[11:]},inplace = True)

# sill_af_df.rename(columns={x: x.split('.')[0]+'. '+x.split('(')[1].split(')')[0] for x in sill_af_df.columns[1:26]},inplace = True)
# sill_af_df.rename(columns= lambda x: col(x),inplace = True)

In [25]:
# sill_be_df = sill_be_df.rename(columns={'id': 'username'})
# sill_af_df = sill_af_df.rename(columns={'id': 'username'})

In [26]:
# sill_be_df.to_csv('./output/sill_be.csv',encoding='utf8', index=False)
# sill_af_df.to_csv('./output/sill_af.csv',encoding='utf8', index=False)