In [1]:
import pandas as pd
import hashlib as hb

In [2]:
vscode = pd.read_csv('./data/1092_viscode_logs.csv')

In [3]:
vscode['username'] = vscode['username'].str.split('@',expand=True).get(0)
vscode = vscode[vscode['username'].str.isdigit() == True]
vscode = vscode[vscode['username'].apply(lambda x: len(str(x))>=9)]

In [4]:
def md5(i):
    hl = hb.md5()
    
    hl.update(str(i).encode(encoding='utf-8'))

    #print('加密前為 ：' + str(i))
    #print('加密後為 ：' + hl.hexdigest())
    
    return hl.hexdigest()

vscode['username'] = vscode['username'].apply(md5)

In [5]:
vscode.drop(columns=["lti.lastName", "lti.name","lti.username","lti.firstName","lti.email","notebookPath","notebookName","notebookName","lti.contextLable","lti.contextTitle"],inplace=True)

In [6]:
vscode.to_csv('./output/vscode.csv',encoding='utf8')

In [7]:
vscode

,_id,_index,_score,_type,cellId,code,codeLength,errorName,errorValue,event,isError,kernelId,lti.contextId,lti.locale,lti.roles,text,timestamp,username
0,NIxRe3sBhZd_WuicrXaC,viscode,NaN,jupyter,NaN,NaN,NaN,NaN,NaN,notebook_open,NaN,NaN,287,zh_tw,Instructor,NaN,"Aug 25, 2021 @ 03:19:15.585",4281b43958059de8ff96710b6a2d947a
1,gkVRe3sB4yEMcndfrQdT,viscode,NaN,jupyter,NaN,NaN,"1,394",NaN,NaN,code_speed,NaN,NaN,287,zh_tw,Instructor,NaN,"Aug 25, 2021 @ 03:19:15.537",4281b43958059de8ff96710b6a2d947a
2,BoxRe3sBhZd_WuicHnYI,viscode,NaN,jupyter,NaN,NaN,NaN,NaN,NaN,tree_open,NaN,NaN,287,zh_tw,Instructor,NaN,"Aug 25, 2021 @ 03:18:38.852",4281b43958059de8ff96710b6a2d947a
3,gzxgXnsB4yEMcndfgGOR,viscode,NaN,jupyter,NaN,NaN,NaN,NaN,NaN,notebook_open,NaN,NaN,288,zh_tw,Learner,NaN,"Aug 19, 2021 @ 12:26:27.856",9879db96946fbb8a3e255ab8815c577e
4,JINgXnsBhZd_WuicgHhR,viscode,NaN,jupyter,NaN,NaN,1,NaN,NaN,code_speed,NaN,NaN,288,zh_tw,Learner,NaN,"Aug 19, 2021 @ 12:26:27.792",9879db96946fbb8a3e255ab8815c577e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27869,QOJdNHoB4yEMcndf2ePR,viscode,NaN,jupyter,5f1af330b9c246478ca1d1662b2ba28a,pur=int(input())\ngift=int(input())\ntmp=pur//...,NaN,NaN,NaN,code_execution,NaN,a44f7387-e046-4ae3-a2d6-c073e944217d,287,zh_tw,Learner,NaN,"Jun 22, 2021 @ 15:36:43.725",a23402a174a55c4211136df4425a724e
27870,Di1dNHoBhZd_WuicsXS1,viscode,NaN,jupyter,5f1af330b9c246478ca1d1662b2ba28a,pur=int(input())\ngift=int(input())\ntmp=pur//...,NaN,NaN,NaN,code_execution,NaN,a44f7387-e046-4ae3-a2d6-c073e944217d,287,zh_tw,Learner,NaN,"Jun 22, 2021 @ 15:36:33.460",a23402a174a55c4211136df4425a724e
27871,FOJdNHoB4yEMcndfNuOS,viscode,NaN,jupyter,5f1af330b9c246478ca1d1662b2ba28a,pur=int(input())\ngift=int(input())\ntmp=pur//...,NaN,NaN,NaN,code_execution,NaN,a44f7387-e046-4ae3-a2d6-c073e944217d,287,zh_tw,Learner,NaN,"Jun 22, 2021 @ 15:36:01.937",a23402a174a55c4211136df4425a724e
27872,6C1dNHoBhZd_WuicJ3Pp,viscode,NaN,jupyter,NaN,NaN,"2,564",NaN,NaN,code_speed,NaN,NaN,287,zh_tw,Learner,NaN,"Jun 22, 2021 @ 15:35:58.184",a23402a174a55c4211136df4425a724e
27873,EOJdNHoB4yEMcndfJeNj,viscode,NaN,jupyter,5f1af330b9c246478ca1d1662b2ba28a,pur=int(input())\ngift=int(input())\ntmp=pur//...,NaN,NaN,NaN,code_execution,NaN,a44f7387-e046-4ae3-a2d6-c073e944217d,287,zh_tw,Learner,NaN,"Jun 22, 2021 @ 15:35:57.537",a23402a174a55c4211136df4425a724e